package com.sdll18.mybatis.mapper;

import com.sdll18.mybatis.pojo.ProjectLayout;
import com.sdll18.mybatis.pojo.ProjectLayoutCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectLayoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    long countByExample(ProjectLayoutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int deleteByExample(ProjectLayoutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int deleteByPrimaryKey(Integer layoutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int insert(ProjectLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int insertSelective(ProjectLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    List<ProjectLayout> selectByExample(ProjectLayoutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    ProjectLayout selectByPrimaryKey(Integer layoutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProjectLayout record, @Param("example") ProjectLayoutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int updateByExample(@Param("record") ProjectLayout record, @Param("example") ProjectLayoutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:20:51 CST 2016
     */
    int updateByPrimaryKey(ProjectLayout record);
}