package com.sdll18.mybatis.mapper;

import com.sdll18.mybatis.pojo.ProjectPhotos;
import com.sdll18.mybatis.pojo.ProjectPhotosCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectPhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    long countByExample(ProjectPhotosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int deleteByExample(ProjectPhotosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int deleteByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int insert(ProjectPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int insertSelective(ProjectPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    List<ProjectPhotos> selectByExample(ProjectPhotosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    ProjectPhotos selectByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProjectPhotos record, @Param("example") ProjectPhotosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int updateByExample(@Param("record") ProjectPhotos record, @Param("example") ProjectPhotosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_photos
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    int updateByPrimaryKey(ProjectPhotos record);
}