package com.sdll18.mybatis.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectLayoutCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public ProjectLayoutCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLayoutIdIsNull() {
            addCriterion("layout_id is null");
            return (Criteria) this;
        }

        public Criteria andLayoutIdIsNotNull() {
            addCriterion("layout_id is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutIdEqualTo(Integer value) {
            addCriterion("layout_id =", value, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdNotEqualTo(Integer value) {
            addCriterion("layout_id <>", value, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdGreaterThan(Integer value) {
            addCriterion("layout_id >", value, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("layout_id >=", value, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdLessThan(Integer value) {
            addCriterion("layout_id <", value, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdLessThanOrEqualTo(Integer value) {
            addCriterion("layout_id <=", value, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdIn(List<Integer> values) {
            addCriterion("layout_id in", values, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdNotIn(List<Integer> values) {
            addCriterion("layout_id not in", values, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdBetween(Integer value1, Integer value2) {
            addCriterion("layout_id between", value1, value2, "layoutId");
            return (Criteria) this;
        }

        public Criteria andLayoutIdNotBetween(Integer value1, Integer value2) {
            addCriterion("layout_id not between", value1, value2, "layoutId");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdIsNull() {
            addCriterion("layout_pic_id is null");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdIsNotNull() {
            addCriterion("layout_pic_id is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdEqualTo(Integer value) {
            addCriterion("layout_pic_id =", value, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdNotEqualTo(Integer value) {
            addCriterion("layout_pic_id <>", value, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdGreaterThan(Integer value) {
            addCriterion("layout_pic_id >", value, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("layout_pic_id >=", value, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdLessThan(Integer value) {
            addCriterion("layout_pic_id <", value, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdLessThanOrEqualTo(Integer value) {
            addCriterion("layout_pic_id <=", value, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdIn(List<Integer> values) {
            addCriterion("layout_pic_id in", values, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdNotIn(List<Integer> values) {
            addCriterion("layout_pic_id not in", values, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdBetween(Integer value1, Integer value2) {
            addCriterion("layout_pic_id between", value1, value2, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutPicIdNotBetween(Integer value1, Integer value2) {
            addCriterion("layout_pic_id not between", value1, value2, "layoutPicId");
            return (Criteria) this;
        }

        public Criteria andLayoutNameIsNull() {
            addCriterion("layout_name is null");
            return (Criteria) this;
        }

        public Criteria andLayoutNameIsNotNull() {
            addCriterion("layout_name is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutNameEqualTo(String value) {
            addCriterion("layout_name =", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameNotEqualTo(String value) {
            addCriterion("layout_name <>", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameGreaterThan(String value) {
            addCriterion("layout_name >", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameGreaterThanOrEqualTo(String value) {
            addCriterion("layout_name >=", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameLessThan(String value) {
            addCriterion("layout_name <", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameLessThanOrEqualTo(String value) {
            addCriterion("layout_name <=", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameLike(String value) {
            addCriterion("layout_name like", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameNotLike(String value) {
            addCriterion("layout_name not like", value, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameIn(List<String> values) {
            addCriterion("layout_name in", values, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameNotIn(List<String> values) {
            addCriterion("layout_name not in", values, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameBetween(String value1, String value2) {
            addCriterion("layout_name between", value1, value2, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutNameNotBetween(String value1, String value2) {
            addCriterion("layout_name not between", value1, value2, "layoutName");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureIsNull() {
            addCriterion("layout_structure is null");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureIsNotNull() {
            addCriterion("layout_structure is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureEqualTo(Integer value) {
            addCriterion("layout_structure =", value, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureNotEqualTo(Integer value) {
            addCriterion("layout_structure <>", value, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureGreaterThan(Integer value) {
            addCriterion("layout_structure >", value, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureGreaterThanOrEqualTo(Integer value) {
            addCriterion("layout_structure >=", value, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureLessThan(Integer value) {
            addCriterion("layout_structure <", value, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureLessThanOrEqualTo(Integer value) {
            addCriterion("layout_structure <=", value, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureIn(List<Integer> values) {
            addCriterion("layout_structure in", values, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureNotIn(List<Integer> values) {
            addCriterion("layout_structure not in", values, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureBetween(Integer value1, Integer value2) {
            addCriterion("layout_structure between", value1, value2, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andLayoutStructureNotBetween(Integer value1, Integer value2) {
            addCriterion("layout_structure not between", value1, value2, "layoutStructure");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaIsNull() {
            addCriterion("building_area is null");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaIsNotNull() {
            addCriterion("building_area is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaEqualTo(BigDecimal value) {
            addCriterion("building_area =", value, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaNotEqualTo(BigDecimal value) {
            addCriterion("building_area <>", value, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaGreaterThan(BigDecimal value) {
            addCriterion("building_area >", value, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("building_area >=", value, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaLessThan(BigDecimal value) {
            addCriterion("building_area <", value, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("building_area <=", value, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaIn(List<BigDecimal> values) {
            addCriterion("building_area in", values, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaNotIn(List<BigDecimal> values) {
            addCriterion("building_area not in", values, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("building_area between", value1, value2, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andBuildingAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("building_area not between", value1, value2, "buildingArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaIsNull() {
            addCriterion("inside_area is null");
            return (Criteria) this;
        }

        public Criteria andInsideAreaIsNotNull() {
            addCriterion("inside_area is not null");
            return (Criteria) this;
        }

        public Criteria andInsideAreaEqualTo(BigDecimal value) {
            addCriterion("inside_area =", value, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaNotEqualTo(BigDecimal value) {
            addCriterion("inside_area <>", value, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaGreaterThan(BigDecimal value) {
            addCriterion("inside_area >", value, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("inside_area >=", value, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaLessThan(BigDecimal value) {
            addCriterion("inside_area <", value, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("inside_area <=", value, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaIn(List<BigDecimal> values) {
            addCriterion("inside_area in", values, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaNotIn(List<BigDecimal> values) {
            addCriterion("inside_area not in", values, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inside_area between", value1, value2, "insideArea");
            return (Criteria) this;
        }

        public Criteria andInsideAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inside_area not between", value1, value2, "insideArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaIsNull() {
            addCriterion("free_area is null");
            return (Criteria) this;
        }

        public Criteria andFreeAreaIsNotNull() {
            addCriterion("free_area is not null");
            return (Criteria) this;
        }

        public Criteria andFreeAreaEqualTo(BigDecimal value) {
            addCriterion("free_area =", value, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaNotEqualTo(BigDecimal value) {
            addCriterion("free_area <>", value, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaGreaterThan(BigDecimal value) {
            addCriterion("free_area >", value, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("free_area >=", value, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaLessThan(BigDecimal value) {
            addCriterion("free_area <", value, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("free_area <=", value, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaIn(List<BigDecimal> values) {
            addCriterion("free_area in", values, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaNotIn(List<BigDecimal> values) {
            addCriterion("free_area not in", values, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("free_area between", value1, value2, "freeArea");
            return (Criteria) this;
        }

        public Criteria andFreeAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("free_area not between", value1, value2, "freeArea");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationIsNull() {
            addCriterion("layout_orientation is null");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationIsNotNull() {
            addCriterion("layout_orientation is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationEqualTo(String value) {
            addCriterion("layout_orientation =", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationNotEqualTo(String value) {
            addCriterion("layout_orientation <>", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationGreaterThan(String value) {
            addCriterion("layout_orientation >", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationGreaterThanOrEqualTo(String value) {
            addCriterion("layout_orientation >=", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationLessThan(String value) {
            addCriterion("layout_orientation <", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationLessThanOrEqualTo(String value) {
            addCriterion("layout_orientation <=", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationLike(String value) {
            addCriterion("layout_orientation like", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationNotLike(String value) {
            addCriterion("layout_orientation not like", value, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationIn(List<String> values) {
            addCriterion("layout_orientation in", values, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationNotIn(List<String> values) {
            addCriterion("layout_orientation not in", values, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationBetween(String value1, String value2) {
            addCriterion("layout_orientation between", value1, value2, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutOrientationNotBetween(String value1, String value2) {
            addCriterion("layout_orientation not between", value1, value2, "layoutOrientation");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureIsNull() {
            addCriterion("layout_feature is null");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureIsNotNull() {
            addCriterion("layout_feature is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureEqualTo(String value) {
            addCriterion("layout_feature =", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureNotEqualTo(String value) {
            addCriterion("layout_feature <>", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureGreaterThan(String value) {
            addCriterion("layout_feature >", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureGreaterThanOrEqualTo(String value) {
            addCriterion("layout_feature >=", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureLessThan(String value) {
            addCriterion("layout_feature <", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureLessThanOrEqualTo(String value) {
            addCriterion("layout_feature <=", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureLike(String value) {
            addCriterion("layout_feature like", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureNotLike(String value) {
            addCriterion("layout_feature not like", value, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureIn(List<String> values) {
            addCriterion("layout_feature in", values, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureNotIn(List<String> values) {
            addCriterion("layout_feature not in", values, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureBetween(String value1, String value2) {
            addCriterion("layout_feature between", value1, value2, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutFeatureNotBetween(String value1, String value2) {
            addCriterion("layout_feature not between", value1, value2, "layoutFeature");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroIsNull() {
            addCriterion("layout_intro is null");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroIsNotNull() {
            addCriterion("layout_intro is not null");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroEqualTo(String value) {
            addCriterion("layout_intro =", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroNotEqualTo(String value) {
            addCriterion("layout_intro <>", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroGreaterThan(String value) {
            addCriterion("layout_intro >", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroGreaterThanOrEqualTo(String value) {
            addCriterion("layout_intro >=", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroLessThan(String value) {
            addCriterion("layout_intro <", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroLessThanOrEqualTo(String value) {
            addCriterion("layout_intro <=", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroLike(String value) {
            addCriterion("layout_intro like", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroNotLike(String value) {
            addCriterion("layout_intro not like", value, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroIn(List<String> values) {
            addCriterion("layout_intro in", values, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroNotIn(List<String> values) {
            addCriterion("layout_intro not in", values, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroBetween(String value1, String value2) {
            addCriterion("layout_intro between", value1, value2, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andLayoutIntroNotBetween(String value1, String value2) {
            addCriterion("layout_intro not between", value1, value2, "layoutIntro");
            return (Criteria) this;
        }

        public Criteria andSaleStatusIsNull() {
            addCriterion("sale_status is null");
            return (Criteria) this;
        }

        public Criteria andSaleStatusIsNotNull() {
            addCriterion("sale_status is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStatusEqualTo(Byte value) {
            addCriterion("sale_status =", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotEqualTo(Byte value) {
            addCriterion("sale_status <>", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusGreaterThan(Byte value) {
            addCriterion("sale_status >", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("sale_status >=", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusLessThan(Byte value) {
            addCriterion("sale_status <", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusLessThanOrEqualTo(Byte value) {
            addCriterion("sale_status <=", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusIn(List<Byte> values) {
            addCriterion("sale_status in", values, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotIn(List<Byte> values) {
            addCriterion("sale_status not in", values, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusBetween(Byte value1, Byte value2) {
            addCriterion("sale_status between", value1, value2, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("sale_status not between", value1, value2, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andAvgIsNull() {
            addCriterion("avg is null");
            return (Criteria) this;
        }

        public Criteria andAvgIsNotNull() {
            addCriterion("avg is not null");
            return (Criteria) this;
        }

        public Criteria andAvgEqualTo(BigDecimal value) {
            addCriterion("avg =", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotEqualTo(BigDecimal value) {
            addCriterion("avg <>", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgGreaterThan(BigDecimal value) {
            addCriterion("avg >", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg >=", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgLessThan(BigDecimal value) {
            addCriterion("avg <", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg <=", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgIn(List<BigDecimal> values) {
            addCriterion("avg in", values, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotIn(List<BigDecimal> values) {
            addCriterion("avg not in", values, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg between", value1, value2, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg not between", value1, value2, "avg");
            return (Criteria) this;
        }

        public Criteria andHighIsNull() {
            addCriterion("high is null");
            return (Criteria) this;
        }

        public Criteria andHighIsNotNull() {
            addCriterion("high is not null");
            return (Criteria) this;
        }

        public Criteria andHighEqualTo(BigDecimal value) {
            addCriterion("high =", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotEqualTo(BigDecimal value) {
            addCriterion("high <>", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThan(BigDecimal value) {
            addCriterion("high >", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("high >=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThan(BigDecimal value) {
            addCriterion("high <", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThanOrEqualTo(BigDecimal value) {
            addCriterion("high <=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighIn(List<BigDecimal> values) {
            addCriterion("high in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotIn(List<BigDecimal> values) {
            addCriterion("high not in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("high between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("high not between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andLowIsNull() {
            addCriterion("low is null");
            return (Criteria) this;
        }

        public Criteria andLowIsNotNull() {
            addCriterion("low is not null");
            return (Criteria) this;
        }

        public Criteria andLowEqualTo(BigDecimal value) {
            addCriterion("low =", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowNotEqualTo(BigDecimal value) {
            addCriterion("low <>", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowGreaterThan(BigDecimal value) {
            addCriterion("low >", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("low >=", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowLessThan(BigDecimal value) {
            addCriterion("low <", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowLessThanOrEqualTo(BigDecimal value) {
            addCriterion("low <=", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowIn(List<BigDecimal> values) {
            addCriterion("low in", values, "low");
            return (Criteria) this;
        }

        public Criteria andLowNotIn(List<BigDecimal> values) {
            addCriterion("low not in", values, "low");
            return (Criteria) this;
        }

        public Criteria andLowBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("low between", value1, value2, "low");
            return (Criteria) this;
        }

        public Criteria andLowNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("low not between", value1, value2, "low");
            return (Criteria) this;
        }

        public Criteria andSumAvgIsNull() {
            addCriterion("sum_avg is null");
            return (Criteria) this;
        }

        public Criteria andSumAvgIsNotNull() {
            addCriterion("sum_avg is not null");
            return (Criteria) this;
        }

        public Criteria andSumAvgEqualTo(BigDecimal value) {
            addCriterion("sum_avg =", value, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgNotEqualTo(BigDecimal value) {
            addCriterion("sum_avg <>", value, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgGreaterThan(BigDecimal value) {
            addCriterion("sum_avg >", value, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_avg >=", value, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgLessThan(BigDecimal value) {
            addCriterion("sum_avg <", value, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_avg <=", value, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgIn(List<BigDecimal> values) {
            addCriterion("sum_avg in", values, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgNotIn(List<BigDecimal> values) {
            addCriterion("sum_avg not in", values, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_avg between", value1, value2, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumAvgNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_avg not between", value1, value2, "sumAvg");
            return (Criteria) this;
        }

        public Criteria andSumHighIsNull() {
            addCriterion("sum_high is null");
            return (Criteria) this;
        }

        public Criteria andSumHighIsNotNull() {
            addCriterion("sum_high is not null");
            return (Criteria) this;
        }

        public Criteria andSumHighEqualTo(BigDecimal value) {
            addCriterion("sum_high =", value, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighNotEqualTo(BigDecimal value) {
            addCriterion("sum_high <>", value, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighGreaterThan(BigDecimal value) {
            addCriterion("sum_high >", value, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_high >=", value, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighLessThan(BigDecimal value) {
            addCriterion("sum_high <", value, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_high <=", value, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighIn(List<BigDecimal> values) {
            addCriterion("sum_high in", values, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighNotIn(List<BigDecimal> values) {
            addCriterion("sum_high not in", values, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_high between", value1, value2, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumHighNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_high not between", value1, value2, "sumHigh");
            return (Criteria) this;
        }

        public Criteria andSumLowIsNull() {
            addCriterion("sum_low is null");
            return (Criteria) this;
        }

        public Criteria andSumLowIsNotNull() {
            addCriterion("sum_low is not null");
            return (Criteria) this;
        }

        public Criteria andSumLowEqualTo(BigDecimal value) {
            addCriterion("sum_low =", value, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowNotEqualTo(BigDecimal value) {
            addCriterion("sum_low <>", value, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowGreaterThan(BigDecimal value) {
            addCriterion("sum_low >", value, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_low >=", value, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowLessThan(BigDecimal value) {
            addCriterion("sum_low <", value, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_low <=", value, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowIn(List<BigDecimal> values) {
            addCriterion("sum_low in", values, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowNotIn(List<BigDecimal> values) {
            addCriterion("sum_low not in", values, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_low between", value1, value2, "sumLow");
            return (Criteria) this;
        }

        public Criteria andSumLowNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_low not between", value1, value2, "sumLow");
            return (Criteria) this;
        }

        public Criteria andPriceTimeIsNull() {
            addCriterion("price_time is null");
            return (Criteria) this;
        }

        public Criteria andPriceTimeIsNotNull() {
            addCriterion("price_time is not null");
            return (Criteria) this;
        }

        public Criteria andPriceTimeEqualTo(Date value) {
            addCriterion("price_time =", value, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeNotEqualTo(Date value) {
            addCriterion("price_time <>", value, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeGreaterThan(Date value) {
            addCriterion("price_time >", value, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("price_time >=", value, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeLessThan(Date value) {
            addCriterion("price_time <", value, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeLessThanOrEqualTo(Date value) {
            addCriterion("price_time <=", value, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeIn(List<Date> values) {
            addCriterion("price_time in", values, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeNotIn(List<Date> values) {
            addCriterion("price_time not in", values, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeBetween(Date value1, Date value2) {
            addCriterion("price_time between", value1, value2, "priceTime");
            return (Criteria) this;
        }

        public Criteria andPriceTimeNotBetween(Date value1, Date value2) {
            addCriterion("price_time not between", value1, value2, "priceTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andEditorIsNull() {
            addCriterion("editor is null");
            return (Criteria) this;
        }

        public Criteria andEditorIsNotNull() {
            addCriterion("editor is not null");
            return (Criteria) this;
        }

        public Criteria andEditorEqualTo(Integer value) {
            addCriterion("editor =", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotEqualTo(Integer value) {
            addCriterion("editor <>", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorGreaterThan(Integer value) {
            addCriterion("editor >", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorGreaterThanOrEqualTo(Integer value) {
            addCriterion("editor >=", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorLessThan(Integer value) {
            addCriterion("editor <", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorLessThanOrEqualTo(Integer value) {
            addCriterion("editor <=", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorIn(List<Integer> values) {
            addCriterion("editor in", values, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotIn(List<Integer> values) {
            addCriterion("editor not in", values, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorBetween(Integer value1, Integer value2) {
            addCriterion("editor between", value1, value2, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotBetween(Integer value1, Integer value2) {
            addCriterion("editor not between", value1, value2, "editor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_layout
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 18 15:41:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_layout
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}