package com.sdll18.mybatis.pojo;

import java.util.Date;

public class ProjectPhotos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.photo_id
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.photo_type
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Integer photoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.pid
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.photo_path
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private String photoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.photo_desc
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private String photoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.photo_name
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private String photoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.photo_alias
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private String photoAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.create_time
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.update_time
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.status
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.creator
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.editor
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Integer editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_photos.display_index
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    private Integer displayIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.photo_id
     *
     * @return the value of project_photos.photo_id
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.photo_id
     *
     * @param photoId the value for project_photos.photo_id
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.photo_type
     *
     * @return the value of project_photos.photo_type
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Integer getPhotoType() {
        return photoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.photo_type
     *
     * @param photoType the value for project_photos.photo_type
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPhotoType(Integer photoType) {
        this.photoType = photoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.pid
     *
     * @return the value of project_photos.pid
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.pid
     *
     * @param pid the value for project_photos.pid
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.photo_path
     *
     * @return the value of project_photos.photo_path
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.photo_path
     *
     * @param photoPath the value for project_photos.photo_path
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.photo_desc
     *
     * @return the value of project_photos.photo_desc
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public String getPhotoDesc() {
        return photoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.photo_desc
     *
     * @param photoDesc the value for project_photos.photo_desc
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPhotoDesc(String photoDesc) {
        this.photoDesc = photoDesc == null ? null : photoDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.photo_name
     *
     * @return the value of project_photos.photo_name
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.photo_name
     *
     * @param photoName the value for project_photos.photo_name
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.photo_alias
     *
     * @return the value of project_photos.photo_alias
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public String getPhotoAlias() {
        return photoAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.photo_alias
     *
     * @param photoAlias the value for project_photos.photo_alias
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setPhotoAlias(String photoAlias) {
        this.photoAlias = photoAlias == null ? null : photoAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.create_time
     *
     * @return the value of project_photos.create_time
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.create_time
     *
     * @param createTime the value for project_photos.create_time
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.update_time
     *
     * @return the value of project_photos.update_time
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.update_time
     *
     * @param updateTime the value for project_photos.update_time
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.status
     *
     * @return the value of project_photos.status
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.status
     *
     * @param status the value for project_photos.status
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.creator
     *
     * @return the value of project_photos.creator
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.creator
     *
     * @param creator the value for project_photos.creator
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.editor
     *
     * @return the value of project_photos.editor
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Integer getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.editor
     *
     * @param editor the value for project_photos.editor
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setEditor(Integer editor) {
        this.editor = editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_photos.display_index
     *
     * @return the value of project_photos.display_index
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public Integer getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_photos.display_index
     *
     * @param displayIndex the value for project_photos.display_index
     *
     * @mbg.generated Tue Oct 18 15:41:26 CST 2016
     */
    public void setDisplayIndex(Integer displayIndex) {
        this.displayIndex = displayIndex;
    }
}